version: 2.1

parameters:
  image_tag:
    type: string
    default: "latest"

executors:
  deploy-executor:
    docker:
      - image: cimg/deploy:current   # <— tag valide (ou remplace par ex: 2024.08)
    working_directory: ~/repo

commands:
  gcp-auth:
    steps:
      - run:
          name: Authenticate to Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project "$GOOGLE_PROJECT_ID"
            gcloud config set compute/region "$GOOGLE_COMPUTE_REGION"
            gcloud auth configure-docker europe-west1-docker.pkg.dev -q

jobs:
  checkout-code:
    executor: deploy-executor
    steps:
      - checkout

  build_docker_image:
    executor: deploy-executor
    environment:
      IMAGE_URI: europe-west1-docker.pkg.dev/${GOOGLE_PROJECT_ID}/mlops-app/mlops-app:<< pipeline.parameters.image_tag >>
    steps:
      - checkout
      - setup_remote_docker
      - gcp-auth
      - run:
          name: Build
          command: docker build -t "$IMAGE_URI" .
      - run:
          name: Push
          command: docker push "$IMAGE_URI"

  deploy_to_gke:
    executor: deploy-executor
    environment:
      IMAGE_URI: europe-west1-docker.pkg.dev/${GOOGLE_PROJECT_ID}/mlops-app/mlops-app:<< pipeline.parameters.image_tag >>
    steps:
      - checkout
      - gcp-auth
      - run:
          name: Get GKE credentials
          command: |
            gcloud container clusters get-credentials "$GKE_CLUSTER" \
              --region "$GOOGLE_COMPUTE_REGION" --project "$GOOGLE_PROJECT_ID"
      - run:
          name: Deploy
          command: |
            kubectl apply -f kubernetes-deployment.yaml
            kubectl rollout status deployment/mlops-app --timeout=120s || true

workflows:
  deploy_pipeline:
    jobs:
      - checkout-code
      - build_docker_image:
          requires: [checkout-code]
      - deploy_to_gke:
          requires: [build_docker_image]
